export const separationItems = [
    {
        id: 1,
        separationDate: '04/07/2023',
        name: 'Heather Sakitsaulo',
        reasonForLeaving: 'Resignation',
        department: '',
        position: '',
        acceptanceLetter: {
            date: '',
            to: '',
            message: '',
        },
        separationLetter: {
            date: '',
            to: '',
            message: '',
        },
        isLetterSent: true,
        isLetterReceived: true,
        letterReceivedDate: "04/07/2023",
        isDocumentsSent: false,
        isDocumentsReceived: false,
        documentReceivedDate: "",
        isLastPayReleased: false,
        isQuitclaimSigned: false,
        isQuitclaimReceived: false,
        quitclaimReceivedDate: "",
    },
    {
        id: 2,
        separationDate: '04/07/2023',
        name: 'Heather Sakitsaulo',
        reasonForLeaving: 'Resignation',
        department: '',
        position: '',
        acceptanceLetter: {
            date: '',
            to: '',
            message: '',
        },
        separationLetter: {
            date: '',
            to: '',
            message: '',
        },
        isLetterSent: false,
        isLetterReceived: false,
        letterReceivedDate: "",
        isDocumentsSent: false,
        isDocumentsReceived: false,
        documentReceivedDate: "",
        isLastPayReleased: false,
        isQuitclaimSigned: false,
        isQuitclaimReceived: false,
        quitclaimReceivedDate: "",
    },
]