const actionTypes = {
  STAGE_REQUIREMENTS: "STAGE_REQUIREMENTS",
  CHECKLIST: "CHECKLIST",
  SEND_EMAIL: "SEND_EMAIL",
  SCHEDULE_INTERVIEW: "SCHEDULE_INTERVIEW",
  DRAG_BLOCK: "DRAG_BLOCK",
  SET_TITLE: "SET_TITLE",
  REMOVE_STAGE: "REMOVE_STAGE",
  ADD_STAGE: "ADD_STAGE",
}

export default actionTypes
