export const separationItems = [
  {
    id: 1,
    separationDate: "2023-04-07",
    name: "Heather Sakitsaulo",
    reasonForLeaving: "Resignation",
    department: "",
    position: "",
    acceptanceLetter: {
      date: "",
      to: "",
      message: "",
    },
    separationLetter: {
      date: "",
      to: "",
      message: "",
    },
    signDocuments: {
      template: "",
      to: "",
      message: "",
    },
    quitclaim: {
      template: "",
      to: "",
      message: "",
    },
    isLetterSent: true,
    isLetterReceived: true,
    letterReceivedDate: "2023-04-07",
    isDocumentsSent: false,
    isDocumentsReceived: false,
    documentReceivedDate: "",
    isLastPayReleased: false,
    isQuitclaimSigned: false,
    isQuitclaimReceived: false,
    quitclaimReceivedDate: "",
  },
  {
    id: 2,
    separationDate: "05/10/2023",
    name: "Heather Sakitsaulo",
    reasonForLeaving: "Resignation",
    department: "",
    position: "",
    acceptanceLetter: {
      date: "",
      to: "",
      message: "",
    },
    separationLetter: {
      date: "",
      to: "",
      message: "",
    },
    signDocuments: {
      template: "",
      to: "",
      message: "",
    },
    quitclaim: {
      template: "",
      to: "",
      message: "",
    },
    isLetterSent: false,
    isLetterReceived: false,
    letterReceivedDate: "",
    isDocumentsSent: false,
    isDocumentsReceived: false,
    documentReceivedDate: "",
    isLastPayReleased: false,
    isQuitclaimSigned: false,
    isQuitclaimReceived: false,
    quitclaimReceivedDate: "",
  },
];

export const employeeIssueItems = [
  {
    id: 1,
    incidentDate: "2023-04-07",
    name: "Heather Sakitsaulo",
    incidentPlace: "WFX",
    department: "",
    position: "",
    briefBackground: "",
    issueNTE: {
      date: "",
      to: "",
      message: "",
    },
    isNTESent: false,
    isNTEReceived: false,
    investigate: {
      date: "",
      witness: "",
      presider: "",
      isEmployeePresent: false,
      result: "",
      decision: "",
      attachment: "",
    },
    isInvestigated: false,
    investigatedDate: "2023-04-07",
    sendDecision: {
      date: "",
      to: "",
      message: "",
    },
    decisionSentDate: "2023-04-07",
    isDecisionSent: false,
    isDecisionReceived: false,
  },
];

export const createMemoPolicyItems = [
  {
    date: "2023-04-07",
    id: 1,
    type: "memo",
    title: "PHIC Update 2023",
    to: "",
    body: "",
    name: "",
    position: "",
    signature: "",
    qrCode: "",
    file: "",
    purpose: "",
    policy: "",
    procedure: "",
    withResponse: false,
    isDeleted: false,
  },
];

export const designBenefitsItems = [
  {
    id: 1,
    title: "",
    to: "",
    purpose: "",
    benefits: "",
    coverage: "",
    eligibility: "",
  },
];
