export const separationItems = [
  {
    id: 1,
    separationDate: "04/07/2023",
    name: "Heather Sakitsaulo",
    reasonForLeaving: "Resignation",
    department: "",
    position: "",
    acceptanceLetter: {
      date: "",
      to: "",
      message: "",
    },
    separationLetter: {
      date: "",
      to: "",
      message: "",
    },
    signDocuments: {
      template: "",
      to: "",
      message: "",
    },
    quitclaim: {
      template: "",
      to: "",
      message: "",
    },
    isLetterSent: true,
    isLetterReceived: true,
    letterReceivedDate: "04/07/2023",
    isDocumentsSent: false,
    isDocumentsReceived: false,
    documentReceivedDate: "",
    isLastPayReleased: false,
    isQuitclaimSigned: false,
    isQuitclaimReceived: false,
    quitclaimReceivedDate: "",
  },
  {
    id: 2,
    separationDate: "05/10/2023",
    name: "Heather Sakitsaulo",
    reasonForLeaving: "Resignation",
    department: "",
    position: "",
    acceptanceLetter: {
      date: "",
      to: "",
      message: "",
    },
    separationLetter: {
      date: "",
      to: "",
      message: "",
    },
    signDocuments: {
      template: "",
      to: "",
      message: "",
    },
    quitclaim: {
      template: "",
      to: "",
      message: "",
    },
    isLetterSent: false,
    isLetterReceived: false,
    letterReceivedDate: "",
    isDocumentsSent: false,
    isDocumentsReceived: false,
    documentReceivedDate: "",
    isLastPayReleased: false,
    isQuitclaimSigned: false,
    isQuitclaimReceived: false,
    quitclaimReceivedDate: "",
  },
];

export const jobPostHistory = [
  {
    id: 1,
    isActive: false,
    JobNo: "000001",
    country: "",
    language: "",
    jobTitle: "Accounting Officer",
    placeAdvertise: "Cagayan de Oro City",
    jobType: "Full-Time",
    schedule: "8 Hour shift",
    hireCount: 2,
    hireDate: "04/07/2023",
    salary: {
      salaryType: "Minimum Amount",
      salaryValue: "20,000",
    },
    rate: "",
    benefits: ["Work from home", "Paid Training", "Flexible Schedule"],
    jobDescription:
      "<p><strong>Ensuring the accounts of the company are accurate and free of error.</strong></p><p><br></p><ul><li>Must have at least 2 years of experience in accounting.</li><li>Any graduate of business course</li><li>Must have attention to details and a good communicator</li></ul>",
    jobDescriptionFile: "",
    postAs: "",
    postAsUpload: "",
    postIn: ["LinkedIn", "Facebook", "Indeed"],
  },

  {
    id: 2,
    date: "04/12/2023",
    isActive: true,
    JobNo: "000002",
    country: "",
    language: "",
    jobTitle: "Software Engineer",
    placeAdvertise: "Cagayan de Oro City",
    jobType: "Full-Time",
    schedule: "8 Hour shift",
    hireCount: 4,
    hireDate: "",
    salary: {
      salaryType: "Exact Amount",
      salaryValue: "20,000",
    },
    rate: "",
    benefits: ["Birthday Leave", "Meal Allowance", "Flexible Schedule"],
    jobDescription:
      "<p><strong>Ensuring the accounts of the company are accurate and free of error.</strong></p><p><br></p><ul><li>Must have at least 2 years of experience in accounting.</li><li>Any graduate of business course</li><li>Must have attention to details and a good communicator</li></ul>",
    jobDescriptionFile: "",
    postAs: "",
    postAsUpload: "",
    postIn: ["LinkedIn", "Facebook", "Indeed", "Twitter", "Instagram"],
  },
];
