// Dummy data for Gig Opportunities and Hire Talent tabs

// Gig Opportunities Dummy Data
export interface GigOpportunity {
  id: number;
  title: string;
  category: string;
  postedDate: string; // e.g., "1 day ago", "3 hours ago"
  clientName: string;
  clientInitials?: string;
  clientPhoto?: string | null;
  rating: number;
  jobsPosted: number; // Number of jobs the client has posted
  skills: string[]; // Required skills/technologies
  budgetMin: number;
  budgetMax: number;
  duration: string; // e.g., "2-3 weeks", "1 week"
  proposalsCount: number;
  description: string;
  requirements?: string[]; // Project requirements as bullet points
  clientId?: number;
}

// Hire Talent Dummy Data (matches Talent type)
export interface Talent {
  id: number;
  name: string;
  title: string;
  rating: number;
  reviews: number;
  jobsDone: number;
  location: string;
  hourlyMin: number;
  hourlyMax: number;
  skills: string[];
  languages: string[];
  availability?: string;
  education?: string;
  about?: string;
  email?: string;
  mobile?: string;
  photo?: string | null;
  portfolio_url?: string | null;
  description?: string | null;
  setup_preference?: string | null;
  expected_salary?: number | null;
}

// Gig Opportunities Dummy Data
export const dummyGigOpportunities: GigOpportunity[] = [
  {
    id: 1,
    title: 'Build a Simple E-commerce Website',
    category: 'Web Development',
    postedDate: '1 day ago',
    clientName: 'Maria Santos',
    clientInitials: 'MS',
    rating: 4.8,
    jobsPosted: 12,
    skills: ['React', 'Node.js', 'E-commerce', 'Payment Integration'],
    budgetMin: 25000,
    budgetMax: 35000,
    duration: '2-3 weeks',
    proposalsCount: 8,
    description: 'I need a simple e-commerce website for my small business selling handmade crafts. The website should be user-friendly and allow customers to browse products, add to cart, and checkout easily.',
    requirements: [
      'Responsive design',
      'Payment gateway integration (GCash, Maya)',
      'Product catalog with categories',
      'Basic inventory management',
    ],
    clientId: 101,
  },
  {
    id: 2,
    title: 'Logo Design for Coffee Shop',
    category: 'Graphic Design',
    postedDate: '3 hours ago',
    clientName: 'Juan dela Cruz',
    clientInitials: 'JD',
    rating: 5.0,
    jobsPosted: 3,
    skills: ['Logo Design', 'Branding', 'Adobe Illustrator'],
    budgetMin: 5000,
    budgetMax: 8000,
    duration: '1 week',
    proposalsCount: 15,
    description: 'Looking for a creative logo design for a new coffee shop opening soon. Need something modern and inviting that represents our brand values.',
    requirements: [
      'Modern and minimalist design',
      'Vector format (AI, SVG)',
      'Color variations (full color, black & white)',
      'Brand guidelines document',
    ],
    clientId: 102,
  },
  {
    id: 3,
    title: 'Ceiling Fan Installation',
    category: 'Home Services',
    postedDate: '5 hours ago',
    clientName: 'Roberto Reyes',
    clientInitials: 'RR',
    rating: 4.5,
    jobsPosted: 7,
    skills: ['Electrical', 'Installation', 'Home Repair'],
    budgetMin: 2000,
    budgetMax: 3500,
    duration: '1 day',
    proposalsCount: 5,
    description: 'Need professional installation of ceiling fan in living room. Must have proper electrical wiring knowledge and tools.',
    requirements: [
      'Licensed electrician preferred',
      'Proper safety equipment',
      'Clean installation',
      'Warranty on work',
    ],
    clientId: 103,
  },
  {
    id: 4,
    title: 'Mobile App Development - React Native',
    category: 'Web Development',
    postedDate: '2 days ago',
    clientName: 'Sarah Garcia',
    clientInitials: 'SG',
    rating: 4.9,
    jobsPosted: 8,
    skills: ['React Native', 'Mobile Development', 'API Integration'],
    budgetMin: 50000,
    budgetMax: 75000,
    duration: '1-2 months',
    proposalsCount: 12,
    description: 'Looking for an experienced React Native developer to build a mobile app for iOS and Android. Must have experience with API integration and state management.',
    requirements: [
      'React Native experience (2+ years)',
      'API integration',
      'State management (Redux/MobX)',
      'App store deployment',
    ],
    clientId: 104,
  },
  {
    id: 5,
    title: 'Video Editing for YouTube Channel',
    category: 'Video Editing',
    postedDate: '6 hours ago',
    clientName: 'Anna Rodriguez',
    clientInitials: 'AR',
    rating: 4.5,
    jobsPosted: 5,
    skills: ['Video Editing', 'Premiere Pro', 'After Effects'],
    budgetMin: 8000,
    budgetMax: 12000,
    duration: '2 weeks',
    proposalsCount: 9,
    description: 'Need a video editor for our YouTube channel. Must be skilled in Premiere Pro or Final Cut Pro. Looking for someone who can create engaging edits with transitions and effects.',
    requirements: [
      'Premiere Pro or Final Cut Pro',
      'Color grading',
      'Motion graphics',
      'Quick turnaround time',
    ],
    clientId: 105,
  },
  {
    id: 6,
    title: 'Copywriting for Product Descriptions',
    category: 'Writing',
    postedDate: '1 day ago',
    clientName: 'Robert Lim',
    clientInitials: 'RL',
    rating: 4.4,
    jobsPosted: 4,
    skills: ['Copywriting', 'SEO Writing', 'E-commerce'],
    budgetMin: 5000,
    budgetMax: 10000,
    duration: '1 week',
    proposalsCount: 7,
    description: 'E-commerce store needs compelling product descriptions written for 50 products. Must be SEO-friendly and conversion-focused. Experience with e-commerce copywriting required.',
    requirements: [
      'SEO-optimized content',
      'Conversion-focused copy',
      'E-commerce experience',
      'Quick delivery',
    ],
    clientId: 106,
  },
  {
    id: 7,
    title: 'Data Entry and Excel Management',
    category: 'Data Entry',
    postedDate: '4 hours ago',
    clientName: 'Lisa Chen',
    clientInitials: 'LC',
    rating: 4.6,
    jobsPosted: 6,
    skills: ['Excel', 'Data Entry', 'Data Analysis'],
    budgetMin: 3000,
    budgetMax: 5000,
    duration: '3-5 days',
    proposalsCount: 11,
    description: 'Need help organizing and entering data into Excel spreadsheets. Must be detail-oriented and proficient in Excel formulas and functions.',
    requirements: [
      'Excel proficiency',
      'Attention to detail',
      'Data validation',
      'Quick turnaround',
    ],
    clientId: 107,
  },
  {
    id: 8,
    title: 'Photography for Corporate Event',
    category: 'Photography',
    postedDate: '1 day ago',
    clientName: 'David Wong',
    clientInitials: 'DW',
    rating: 4.9,
    jobsPosted: 10,
    skills: ['Event Photography', 'Corporate Events', 'Photo Editing'],
    budgetMin: 20000,
    budgetMax: 30000,
    duration: '1 day',
    proposalsCount: 6,
    description: 'Corporate event photography needed for company anniversary. Must have professional camera equipment and experience with event photography. Deliverables include edited photos.',
    requirements: [
      'Professional camera equipment',
      'Event photography experience',
      'Photo editing',
      'High-resolution images',
    ],
    clientId: 108,
  },
];

// Hire Talent Dummy Data
export const dummyTalents: Talent[] = [
  {
    id: 1,
    name: 'Carlo Mendoza',
    title: 'Full-Stack Developer',
    rating: 4.9,
    reviews: 47,
    jobsDone: 52,
    location: 'Cagayan de Oro City',
    hourlyMin: 800,
    hourlyMax: 1200,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Computer Science - UP Diliman',
    about: 'Senior developer with 8 years of experience building scalable web applications. Specialized in fintech and e-commerce solutions.',
    email: 'carlo.mendoza@example.com',
    mobile: '+63 912 345 6789',
    photo: null,
    portfolio_url: 'https://carlomendoza.dev',
    description: 'Passionate developer who loves creating innovative solutions',
    setup_preference: 'Hybrid',
    expected_salary: 100000,
  },
  {
    id: 2,
    name: 'Patricia Lim',
    title: 'UI/UX Designer',
    rating: 5.0,
    reviews: 31,
    jobsDone: 38,
    location: 'Cebu City',
    hourlyMin: 600,
    hourlyMax: 900,
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Industrial Design, De La Salle University',
    about: 'Creative UI/UX designer with a passion for user-centered design. Expert in creating intuitive interfaces and conducting user research.',
    email: 'patricia.lim@example.com',
    mobile: '+63 923 456 7890',
    photo: null,
    portfolio_url: 'https://patricialim.design',
    description: 'Designing experiences that users love',
    setup_preference: 'Work from Home',
    expected_salary: 70000,
  },
  {
    id: 3,
    name: 'Miguel Torres',
    title: 'Licensed Electrician',
    rating: 4.7,
    reviews: 89,
    jobsDone: 156,
    location: 'Butuan City',
    hourlyMin: 350,
    hourlyMax: 500,
    skills: ['Electrical Wiring', 'Installation', 'Troubleshooting', 'Solar Panels'],
    languages: ['English', 'Filipino', 'Cebuano'],
    availability: 'Available Now',
    education: 'BS Electrical Engineering, Mindanao State University',
    about: 'Licensed electrician with 15+ years of experience in residential and commercial electrical work. Expert in troubleshooting and solar panel installation.',
    email: 'miguel.torres@example.com',
    mobile: '+63 934 567 8901',
    photo: null,
    portfolio_url: null,
    description: 'Reliable electrical services you can trust',
    setup_preference: 'On-site',
    expected_salary: 40000,
  },
  {
    id: 4,
    name: 'Jennifer Martinez',
    title: 'Senior Full Stack Developer',
    rating: 4.9,
    reviews: 45,
    jobsDone: 67,
    location: 'Makati City, Metro Manila',
    hourlyMin: 1500,
    hourlyMax: 2500,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    languages: ['English', 'Filipino', 'Spanish'],
    availability: 'Available Now',
    education: 'BS Computer Science, University of the Philippines',
    about: 'Experienced full-stack developer with 8+ years of experience building scalable web applications. Specialized in React, Node.js, and cloud infrastructure.',
    email: 'jennifer.martinez@example.com',
    mobile: '+63 912 345 6789',
    photo: null,
    portfolio_url: 'https://jennifermartinez.dev',
    description: 'Passionate developer who loves creating innovative solutions',
    setup_preference: 'Hybrid',
    expected_salary: 120000,
  },
  {
    id: 2,
    name: 'Carlos Reyes',
    title: 'UI/UX Designer',
    rating: 4.8,
    reviews: 38,
    jobsDone: 52,
    location: 'Quezon City, Metro Manila',
    hourlyMin: 1200,
    hourlyMax: 2000,
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'Design Systems'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Industrial Design, De La Salle University',
    about: 'Creative UI/UX designer with a passion for user-centered design. Expert in creating intuitive interfaces and conducting user research.',
    email: 'carlos.reyes@example.com',
    mobile: '+63 923 456 7890',
    photo: null,
    portfolio_url: 'https://carlosreyes.design',
    description: 'Designing experiences that users love',
    setup_preference: 'Work from Home',
    expected_salary: 80000,
  },
  {
    id: 3,
    name: 'Maria Fernandez',
    title: 'Digital Marketing Specialist',
    rating: 4.7,
    reviews: 42,
    jobsDone: 58,
    location: 'Taguig City, Metro Manila',
    hourlyMin: 800,
    hourlyMax: 1500,
    skills: ['SEO', 'SEM', 'Social Media Marketing', 'Content Strategy', 'Analytics'],
    languages: ['English', 'Filipino', 'Tagalog'],
    availability: 'Available in 1 week',
    education: 'BS Marketing, Ateneo de Manila University',
    about: 'Results-driven digital marketer with expertise in SEO, SEM, and social media campaigns. Proven track record of increasing brand visibility and engagement.',
    email: 'maria.fernandez@example.com',
    mobile: '+63 934 567 8901',
    photo: null,
    portfolio_url: 'https://mariafernandez.marketing',
    description: 'Helping brands grow their online presence',
    setup_preference: 'Hybrid',
    expected_salary: 60000,
  },
  {
    id: 4,
    name: 'James Anderson',
    title: 'Mobile App Developer',
    rating: 4.9,
    reviews: 35,
    jobsDone: 48,
    location: 'Pasig City, Metro Manila',
    hourlyMin: 1800,
    hourlyMax: 3000,
    skills: ['React Native', 'Flutter', 'iOS Development', 'Android Development', 'Firebase'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Computer Engineering, Mapua University',
    about: 'Mobile app developer specializing in cross-platform development. Expert in React Native and Flutter with a focus on performance optimization.',
    email: 'james.anderson@example.com',
    mobile: '+63 945 678 9012',
    photo: null,
    portfolio_url: 'https://jamesanderson.dev',
    description: 'Building mobile apps that users love',
    setup_preference: 'Work from Home',
    expected_salary: 150000,
  },
  {
    id: 5,
    name: 'Patricia Cruz',
    title: 'Content Writer & Copywriter',
    rating: 4.6,
    reviews: 29,
    jobsDone: 41,
    location: 'Mandaluyong City, Metro Manila',
    hourlyMin: 500,
    hourlyMax: 1000,
    skills: ['Content Writing', 'Copywriting', 'SEO Writing', 'Blog Writing', 'Technical Writing'],
    languages: ['English', 'Filipino', 'Tagalog'],
    availability: 'Available Now',
    education: 'BA Communication Arts, University of Santo Tomas',
    about: 'Versatile content writer with expertise in creating engaging copy for websites, blogs, and marketing materials. Strong SEO knowledge and ability to adapt writing style.',
    email: 'patricia.cruz@example.com',
    mobile: '+63 956 789 0123',
    photo: null,
    portfolio_url: 'https://patriciacruz.writing',
    description: 'Words that convert and engage',
    setup_preference: 'Work from Home',
    expected_salary: 40000,
  },
  {
    id: 6,
    name: 'Roberto Santos',
    title: 'Video Editor & Motion Graphics',
    rating: 4.8,
    reviews: 33,
    jobsDone: 46,
    location: 'Manila City, Metro Manila',
    hourlyMin: 1000,
    hourlyMax: 1800,
    skills: ['Premiere Pro', 'After Effects', 'Final Cut Pro', 'Motion Graphics', 'Color Grading'],
    languages: ['English', 'Filipino'],
    availability: 'Available in 2 weeks',
    education: 'BS Multimedia Arts, De La Salle-College of Saint Benilde',
    about: 'Creative video editor and motion graphics artist with a passion for storytelling through visuals. Expert in creating engaging video content for various platforms.',
    email: 'roberto.santos@example.com',
    mobile: '+63 967 890 1234',
    photo: null,
    portfolio_url: 'https://robertosantos.video',
    description: 'Bringing stories to life through video',
    setup_preference: 'Hybrid',
    expected_salary: 70000,
  },
  {
    id: 7,
    name: 'Angela Lopez',
    title: 'Graphic Designer',
    rating: 4.7,
    reviews: 27,
    jobsDone: 39,
    location: 'San Juan City, Metro Manila',
    hourlyMin: 700,
    hourlyMax: 1200,
    skills: ['Photoshop', 'Illustrator', 'InDesign', 'Branding', 'Print Design'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Fine Arts, University of the Philippines',
    about: 'Creative graphic designer specializing in branding and print design. Passionate about creating visually appealing designs that communicate brand identity effectively.',
    email: 'angela.lopez@example.com',
    mobile: '+63 978 901 2345',
    photo: null,
    portfolio_url: 'https://angelalopez.design',
    description: 'Designing brands that stand out',
    setup_preference: 'Work from Home',
    expected_salary: 50000,
  },
  {
    id: 8,
    name: 'Michael Torres',
    title: 'Data Analyst & Business Intelligence',
    rating: 4.9,
    reviews: 31,
    jobsDone: 44,
    location: 'BGC, Taguig City',
    hourlyMin: 1300,
    hourlyMax: 2200,
    skills: ['SQL', 'Python', 'Tableau', 'Power BI', 'Data Visualization', 'Excel'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Statistics, University of the Philippines',
    about: 'Data analyst with expertise in transforming raw data into actionable insights. Skilled in SQL, Python, and various BI tools. Strong background in statistical analysis.',
    email: 'michael.torres@example.com',
    mobile: '+63 989 012 3456',
    photo: null,
    portfolio_url: 'https://michaeltorres.analytics',
    description: 'Turning data into decisions',
    setup_preference: 'Hybrid',
    expected_salary: 90000,
  },
];

