// Hire Talent Dummy Data

export interface Talent {
  id: number;
  name: string;
  title: string;
  rating: number;
  reviews: number;
  jobsDone: number;
  location: string;
  hourlyMin: number;
  hourlyMax: number;
  skills: string[];
  languages: string[];
  availability?: string;
  education?: string;
  about?: string;
  email?: string;
  mobile?: string;
  photo?: string | null;
  portfolio_url?: string | null;
  description?: string | null;
  setup_preference?: string | null;
  expected_salary?: number | null;
}

// Hire Talent Dummy Data
export const dummyTalents: Talent[] = [
  {
    id: 1,
    name: 'Carlo Mendoza',
    title: 'Full-Stack Developer',
    rating: 4.9,
    reviews: 47,
    jobsDone: 52,
    location: 'Cagayan de Oro City',
    hourlyMin: 800,
    hourlyMax: 1200,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Computer Science - UP Diliman',
    about: 'Senior developer with 8 years of experience building scalable web applications. Specialized in fintech and e-commerce solutions.',
    email: 'carlo.mendoza@example.com',
    mobile: '+63 912 345 6789',
    photo: null,
    portfolio_url: 'https://carlomendoza.dev',
    description: 'Passionate developer who loves creating innovative solutions',
    setup_preference: 'Hybrid',
    expected_salary: 100000,
  },
  {
    id: 2,
    name: 'Patricia Lim',
    title: 'UI/UX Designer',
    rating: 5.0,
    reviews: 31,
    jobsDone: 38,
    location: 'Cebu City',
    hourlyMin: 600,
    hourlyMax: 900,
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Industrial Design, De La Salle University',
    about: 'Creative UI/UX designer with a passion for user-centered design. Expert in creating intuitive interfaces and conducting user research.',
    email: 'patricia.lim@example.com',
    mobile: '+63 923 456 7890',
    photo: null,
    portfolio_url: 'https://patricialim.design',
    description: 'Designing experiences that users love',
    setup_preference: 'Work from Home',
    expected_salary: 70000,
  },
  {
    id: 3,
    name: 'Miguel Torres',
    title: 'Licensed Electrician',
    rating: 4.7,
    reviews: 89,
    jobsDone: 156,
    location: 'Butuan City',
    hourlyMin: 350,
    hourlyMax: 500,
    skills: ['Electrical Wiring', 'Installation', 'Troubleshooting', 'Solar Panels'],
    languages: ['English', 'Filipino', 'Cebuano'],
    availability: 'Available Now',
    education: 'BS Electrical Engineering, Mindanao State University',
    about: 'Licensed electrician with 15+ years of experience in residential and commercial electrical work. Expert in troubleshooting and solar panel installation.',
    email: 'miguel.torres@example.com',
    mobile: '+63 934 567 8901',
    photo: null,
    portfolio_url: null,
    description: 'Reliable electrical services you can trust',
    setup_preference: 'On-site',
    expected_salary: 40000,
  },
  {
    id: 4,
    name: 'Jennifer Martinez',
    title: 'Senior Full Stack Developer',
    rating: 4.9,
    reviews: 45,
    jobsDone: 67,
    location: 'Makati City, Metro Manila',
    hourlyMin: 1500,
    hourlyMax: 2500,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    languages: ['English', 'Filipino', 'Spanish'],
    availability: 'Available Now',
    education: 'BS Computer Science, University of the Philippines',
    about: 'Experienced full-stack developer with 8+ years of experience building scalable web applications. Specialized in React, Node.js, and cloud infrastructure.',
    email: 'jennifer.martinez@example.com',
    mobile: '+63 912 345 6789',
    photo: null,
    portfolio_url: 'https://jennifermartinez.dev',
    description: 'Passionate developer who loves creating innovative solutions',
    setup_preference: 'Hybrid',
    expected_salary: 120000,
  },
  {
    id: 5,
    name: 'Carlos Reyes',
    title: 'UI/UX Designer',
    rating: 4.8,
    reviews: 38,
    jobsDone: 52,
    location: 'Quezon City, Metro Manila',
    hourlyMin: 1200,
    hourlyMax: 2000,
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'Design Systems'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Industrial Design, De La Salle University',
    about: 'Creative UI/UX designer with a passion for user-centered design. Expert in creating intuitive interfaces and conducting user research.',
    email: 'carlos.reyes@example.com',
    mobile: '+63 923 456 7890',
    photo: null,
    portfolio_url: 'https://carlosreyes.design',
    description: 'Designing experiences that users love',
    setup_preference: 'Work from Home',
    expected_salary: 80000,
  },
  {
    id: 6,
    name: 'Maria Fernandez',
    title: 'Digital Marketing Specialist',
    rating: 4.7,
    reviews: 42,
    jobsDone: 58,
    location: 'Taguig City, Metro Manila',
    hourlyMin: 800,
    hourlyMax: 1500,
    skills: ['SEO', 'SEM', 'Social Media Marketing', 'Content Strategy', 'Analytics'],
    languages: ['English', 'Filipino', 'Tagalog'],
    availability: 'Available in 1 week',
    education: 'BS Marketing, Ateneo de Manila University',
    about: 'Results-driven digital marketer with expertise in SEO, SEM, and social media campaigns. Proven track record of increasing brand visibility and engagement.',
    email: 'maria.fernandez@example.com',
    mobile: '+63 934 567 8901',
    photo: null,
    portfolio_url: 'https://mariafernandez.marketing',
    description: 'Helping brands grow their online presence',
    setup_preference: 'Hybrid',
    expected_salary: 60000,
  },
  {
    id: 7,
    name: 'James Anderson',
    title: 'Mobile App Developer',
    rating: 4.9,
    reviews: 35,
    jobsDone: 48,
    location: 'Pasig City, Metro Manila',
    hourlyMin: 1800,
    hourlyMax: 3000,
    skills: ['React Native', 'Flutter', 'iOS Development', 'Android Development', 'Firebase'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Computer Engineering, Mapua University',
    about: 'Mobile app developer specializing in cross-platform development. Expert in React Native and Flutter with a focus on performance optimization.',
    email: 'james.anderson@example.com',
    mobile: '+63 945 678 9012',
    photo: null,
    portfolio_url: 'https://jamesanderson.dev',
    description: 'Building mobile apps that users love',
    setup_preference: 'Work from Home',
    expected_salary: 150000,
  },
  {
    id: 8,
    name: 'Patricia Cruz',
    title: 'Content Writer & Copywriter',
    rating: 4.6,
    reviews: 29,
    jobsDone: 41,
    location: 'Mandaluyong City, Metro Manila',
    hourlyMin: 500,
    hourlyMax: 1000,
    skills: ['Content Writing', 'Copywriting', 'SEO Writing', 'Blog Writing', 'Technical Writing'],
    languages: ['English', 'Filipino', 'Tagalog'],
    availability: 'Available Now',
    education: 'BA Communication Arts, University of Santo Tomas',
    about: 'Versatile content writer with expertise in creating engaging copy for websites, blogs, and marketing materials. Strong SEO knowledge and ability to adapt writing style.',
    email: 'patricia.cruz@example.com',
    mobile: '+63 956 789 0123',
    photo: null,
    portfolio_url: 'https://patriciacruz.writing',
    description: 'Words that convert and engage',
    setup_preference: 'Work from Home',
    expected_salary: 40000,
  },
  {
    id: 9,
    name: 'Roberto Santos',
    title: 'Video Editor & Motion Graphics',
    rating: 4.8,
    reviews: 33,
    jobsDone: 46,
    location: 'Manila City, Metro Manila',
    hourlyMin: 1000,
    hourlyMax: 1800,
    skills: ['Premiere Pro', 'After Effects', 'Final Cut Pro', 'Motion Graphics', 'Color Grading'],
    languages: ['English', 'Filipino'],
    availability: 'Available in 2 weeks',
    education: 'BS Multimedia Arts, De La Salle-College of Saint Benilde',
    about: 'Creative video editor and motion graphics artist with a passion for storytelling through visuals. Expert in creating engaging video content for various platforms.',
    email: 'roberto.santos@example.com',
    mobile: '+63 967 890 1234',
    photo: null,
    portfolio_url: 'https://robertosantos.video',
    description: 'Bringing stories to life through video',
    setup_preference: 'Hybrid',
    expected_salary: 70000,
  },
  {
    id: 10,
    name: 'Angela Lopez',
    title: 'Graphic Designer',
    rating: 4.7,
    reviews: 27,
    jobsDone: 39,
    location: 'San Juan City, Metro Manila',
    hourlyMin: 700,
    hourlyMax: 1200,
    skills: ['Photoshop', 'Illustrator', 'InDesign', 'Branding', 'Print Design'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Fine Arts, University of the Philippines',
    about: 'Creative graphic designer specializing in branding and print design. Passionate about creating visually appealing designs that communicate brand identity effectively.',
    email: 'angela.lopez@example.com',
    mobile: '+63 978 901 2345',
    photo: null,
    portfolio_url: 'https://angelalopez.design',
    description: 'Designing brands that stand out',
    setup_preference: 'Work from Home',
    expected_salary: 50000,
  },
  {
    id: 11,
    name: 'Michael Torres',
    title: 'Data Analyst & Business Intelligence',
    rating: 4.9,
    reviews: 31,
    jobsDone: 44,
    location: 'BGC, Taguig City',
    hourlyMin: 1300,
    hourlyMax: 2200,
    skills: ['SQL', 'Python', 'Tableau', 'Power BI', 'Data Visualization', 'Excel'],
    languages: ['English', 'Filipino'],
    availability: 'Available Now',
    education: 'BS Statistics, University of the Philippines',
    about: 'Data analyst with expertise in transforming raw data into actionable insights. Skilled in SQL, Python, and various BI tools. Strong background in statistical analysis.',
    email: 'michael.torres@example.com',
    mobile: '+63 989 012 3456',
    photo: null,
    portfolio_url: 'https://michaeltorres.analytics',
    description: 'Turning data into decisions',
    setup_preference: 'Hybrid',
    expected_salary: 90000,
  },
];

